import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/ui/navigation";
import { createClient } from "@/lib/supabase/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();

  // 서버 사이드에서 사용자 정보 가져오기
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // 디버깅: 서버에서 가져온 사용자 정보 확인
  console.log("Layout - 서버에서 가져온 user:", user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation
          initialUser={user ? { id: user.id, email: user.email } : null}
        />
        {children}
      </body>
    </html>
  );
}
